# Aliases
alias home='cd ~'
alias root='cd /'
alias dtop='cd $HOME/Desktop'
alias projects='cd $HOME/Documents/dev/projects'
alias docs='cd $HOME/Documents'
alias notes='cd $HOME/Documents/Notes'
alias todo='$EDITOR $HOME/todo.txt'
alias o=open
alias ..='cd ..'
alias ...='cd ..; cd ..'
alias ....='cd ..; cd ..; cd ..'
alias q='exit'
alias c='clear'
# Enable ls deluxe for better directory formatting
alias ls='lsd'
alias cs='clear; ls'
alias lsa='ls -a'
alias lsl='ls -l'
alias t='time'
alias k='kill'
# Let grep be colorful
alias grep='grep --color=auto'
alias bashrc='$EDITOR $HOME/.bashrc'
alias vimrc='$EDITOR $HOME/.vimrc'
alias zshrc='$EDITOR $HOME/.zshrc'
